# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# assigns reviewers to pull requests in a similar way as CODEOWNERS, but doesn't require reviewers
# to have write access to the repository
# see .github/component_owners.yaml for the list of components and their owners
name: Assign reviewers

on:
  # pull_request_target is needed instead of just pull_request
  # because repository write permission is needed to assign reviewers
  pull_request_target:

jobs:
  assign-reviewers:
    if: github.repository == 'open-telemetry/opentelemetry-demo'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: dyladan/component-owners@58bd86e9814d23f1525d0a970682cead459fa783 # main
        with:
          # using this action to request review only (not assignment)
          assign-owners: false
