# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# adds a label to a pull request if certain files are changed
name: Label Pull Requests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check for changed files
        id: file_changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          list-files: shell
          filters: |
            docsUpdateRequired:
              - 'src/flagd/**'
            helmUpdateRequired:
              - '.env'
              - 'docker-compose*.yml'
              - 'src/flagd/**'
              - 'src/grafana/**'
              - 'src/otel-collector/**'
              - 'src/prometheus/**'

      - name: "Add Label: docs-update-required"
        if: steps.file_changes.outputs.docsUpdateRequired == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const issue_number = context.issue.number;
            github.rest.issues.addLabels({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['docs-update-required']
            })

      - name: "Add Label: helm-update-required"
        if: steps.file_changes.outputs.helmUpdateRequired == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const issue_number = context.issue.number;
            github.rest.issues.addLabels({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['helm-update-required']
            })
